# Generated by Django 3.2.2 on 2021-05-15 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fligts',
            new_name='Flights',
        ),
    ]
