# Generated by Django 3.2.2 on 2021-05-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='first',
            field=models.CharField(max_length=66),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last',
            field=models.CharField(max_length=66),
        ),
    ]
